// Generated by CoffeeScript 1.7.1
(function() {
  var StormAgent, agent, argv, config, storm, _ref, _ref1, _ref2;

  argv = require('minimist')(process.argv.slice(2));

  if (argv.h != null) {
    console.log("-h view this help\n-p port number\n-l logfile\n-d datadir");
    return;
  }

  config = {};

  config.port = (_ref = argv.p) != null ? _ref : 5000;

  config.logfile = (_ref1 = argv.l) != null ? _ref1 : "/var/log/stormagent.log";

  config.datadir = (_ref2 = argv.d) != null ? _ref2 : "/var/stormstack";

  storm = {
    provider: null,
    tracker: null,
    skey: null,
    id: null,
    bolt: {
      cert: "",
      key: "",
      ca: "",
      uplinks: ["bolt://stormtower.dev.intercloud.net"],
      uplinkStrategy: "round-robin",
      allowRelay: true,
      relayPort: 8017,
      allowedPorts: [5000],
      listenPort: 443,
      beaconInterval: 10,
      beaconRetry: 3
    }
  };

  StormAgent = require('./stormagent');

  agent = new StormAgent(config);

  agent.on("running", function() {
    this.log("unit testing...");
    this.log("#1 - agent.env.discover", this.env.discover());
    this.log("#2 - agent.env.os", this.env.os());
    this.log("#3 - agent.activate");
    return this.activate(storm, (function(_this) {
      return function(err, status) {
        return _this.log("activation completed with", status);
      };
    })(this));
  });

  agent.on("activated", function(storm) {
    return this.log("activated with:", storm);
  });

  agent.run();

}).call(this);
