// Generated by CoffeeScript 1.4.0
(function() {
  var EventEmitter, StormAgent, StormData, StormRegistry, async, stormlog, util, uuid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  util = require('util');

  stormlog = function(message, obj) {
    var out;
    if (message != null) {
      out = "" + this.constructor.name + ": " + message;
    }
    if (obj != null) {
      out += "\n" + util.inspect(obj);
    }
    if (out != null) {
      return util.log(out);
    }
  };

  uuid = require('node-uuid');

  StormData = (function() {
    var validate;

    validate = require('json-schema').validate;

    function StormData(id, data, schema) {
      var res, _ref;
      this.id = id;
      this.data = data;
      res = validate(data, schema);
      if (!res.valid) {
        throw new Error("unable to validate passed in data during StormData creation! " + util.inspect(res));
      }
      if ((_ref = this.id) == null) {
        this.id = uuid.v4();
      }
      if (data != null) {
        this.validity = data.validity;
      }
      this.saved = false;
    }

    return StormData;

  })();

  async = require('async');

  StormRegistry = (function(_super) {

    __extends(StormRegistry, _super);

    function StormRegistry(filename) {
      var _this = this;
      this.log = stormlog;
      this.running = true;
      this.entries = [];
      if (filename) {
        this.db = require('dirty')("" + filename);
        this.db._writeStream.on('error', function(err) {
          return _this.log(err);
        });
        this.db._writeStream.on('open', function() {
          _this.log('loaded #{filename}');
          return _this.db.forEach(function(key, val) {
            if (val != null) {
              _this.log('found ' + key);
            }
            if (val != null) {
              return _this.emit('load', key, val);
            }
          });
        });
      }
    }

    StormRegistry.prototype.add = function(key, entry) {
      var data, _ref, _ref1;
      if (entry == null) {
        return;
      }
      this.log("adding " + entry.id + " into entries");
      if ((_ref = entry.id) == null) {
        entry.id = key != null ? key : uuid.v4();
      }
      if ((_ref1 = entry.saved) == null) {
        entry.saved = typeof saved !== "undefined" && saved !== null ? saved : false;
      }
      if ((this.db != null) && !entry.saved) {
        data = entry;
        if (entry instanceof StormData) {
          data = entry.data;
        }
        this.db.set(entry.id, data);
        entry.saved = true;
      }
      this.entries[entry.id] = entry;
      this.emit('added', entry);
      return entry;
    };

    StormRegistry.prototype.get = function(key) {
      return this.entries[key];
    };

    StormRegistry.prototype.remove = function(key) {
      this.log("removing " + key + " from entries");
      this.emit('removed', this.entries[key]);
      return delete this.entries[key];
    };

    StormRegistry.prototype.list = function() {
      var key, _results;
      _results = [];
      for (key in this.entries) {
        _results.push(this.get(key));
      }
      return _results;
    };

    StormRegistry.prototype.expires = function(interval) {
      var _this = this;
      return async.whilst(function() {
        return _this.running;
      }, function(repeat) {
        var entry, key, _fn, _ref;
        _ref = _this.entries;
        _fn = function(key, entry) {
          _this.log("DEBUG: " + key + " has validity=" + entry.validity);
          _this.entries[key].validity -= interval / 1000;
          if (!(entry.validity > 1)) {
            _this.remove(key);
            return _this.emit("expired", entry);
          }
        };
        for (key in _ref) {
          entry = _ref[key];
          if (entry == null) {
            _this.remove(key);
            continue;
          }
          _fn(key, entry);
        }
        return setTimeout(repeat, interval);
      }, function(err) {
        return _this.log("stormregistry stopped, validity checker stopping...");
      });
    };

    return StormRegistry;

  })(EventEmitter);

  StormAgent = (function(_super) {
    var extend, fs, path, validate;

    __extends(StormAgent, _super);

    validate = require('json-schema').validate;

    fs = require('fs');

    path = require('path');

    extend = require('util')._extend;

    function StormAgent(config) {
      var _ref, _ref1,
        _this = this;
      this.log = stormlog;
      this.newdb = function(filename, callback) {};
      this.timestamp = function() {
        var d, months, pad, time;
        d = new Date();
        pad = function(n) {
          var sn;
          sn = n.toString(10);
          if (n < 10) {
            sn = '0' + sn;
          }
          return sn;
        };
        time = [pad(d.getHours()), pad(d.getMinutes()), pad(d.getSeconds())].join(':');
        months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        return [d.getDate(), months[d.getMonth()], time].join(' ');
      };
      uuid = require('node-uuid');
      this.state = {
        id: null,
        instance: uuid.v4(),
        activated: false,
        running: false,
        env: null
      };
      if ((_ref = this.config) == null) {
        this.config = {};
      }
      if ((_ref1 = this.functions) == null) {
        this.functions = [];
      }
      this["import"](module);
      if (config != null) {
        this.config = extend(this.config, config);
      }
      this.log("agent.config", this.config);
      this.log("agent.functions", this.functions);
      this.env = require('./environment');
      /*
              @log "setting up directories..."
              fs=require('fs')
              try
                  fs.mkdirSync("#{config.datadir}") unless fs.existsSync("#{config.datadir}")
                  fs.mkdirSync("#{config.datadir}/db")  unless fs.existsSync("#{config.datadir}/db")
                  fs.mkdirSync("#{config.datadir}/certs") unless fs.existsSync("#{config.datadir}/certs")
              catch error
                  util.log "Error in creating data dirs"
      */

      this.on('running', function(include) {
        _this.include = include;
        return _this.state.running = true;
      });
    }

    StormAgent.prototype.status = function() {
      this.state.config = JSON.parse(JSON.stringify(this.config));
      delete this.state.config.ca;
      delete this.state.config.cert;
      delete this.state.config.key;
      this.state.os = this.env.os();
      return this.state;
    };

    StormAgent.prototype.run = function() {
      var _agent, _ref;
      _agent = this;
      this.log('running with: ', this.config);
      return _ref = require('zappajs')(this.config.port, function() {
        var logger, morgan,
          _this = this;
        morgan = require('morgan');
        morgan.token('date', _agent.timestamp);
        logger = morgan(":date - :method :url :status :response-time ms - :remote-addr");
        this.configure(function() {
          _this.use('bodyParser', 'methodOverride', logger, require("passport").initialize(), _this.app.router, 'static');
          _this.set({
            'basepath': '/v1.0'
          });
          return _this.set({
            'agent': _agent
          });
        });
        this.configure({
          development: function() {
            return _this.use({
              errorHandler: {
                dumpExceptions: true,
                showStack: true
              }
            });
          },
          production: function() {
            return _this.use('errorHandler');
          }
        });
        this.enable('serve jquery', 'minify');
        return _agent.emit('running', this.include);
      }), this.app = _ref.app, _ref;
    };

    StormAgent.prototype["import"] = function(id) {
      var p, pkgconfig, plugfile, plugin, self, storm, _i, _len, _ref, _ref1,
        _this = this;
      if (id instanceof Object && (id.filename != null)) {
        self = true;
        id = p = id.filename;
        while ((p = path.dirname(p)) && p !== path.sep && !fs.existsSync("" + p + "/package.json")) {
          this.log("checking " + p + "...");
        }
        if (p !== path.sep) {
          id = p;
        }
      }
      try {
        pkgconfig = require("" + id + "/package.json").config;
        storm = pkgconfig.storm;
        this.log("import - [" + id + "] processing storm compatible module...");
        if (storm.functions != null) {
          this.log("import - [" + id + "] extending config and functions...");
          if (!this.state.running) {
            this.config = extend(this.config, pkgconfig);
          }
          delete this.config.storm;
          this.log("import - [" + id + "] available functions:", storm.functions);
          if (storm.functions != null) {
            (_ref = this.functions).push.apply(_ref, storm.functions);
          }
        }
        if (storm.plugins != null) {
          this.log("import - [" + id + "] available plugins:", storm.plugins);
          _ref1 = storm.plugins;
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            plugfile = _ref1[_i];
            plugin = require("" + id + "/" + plugfile);
            if (!plugin) {
              continue;
            }
            this.log("import - [" + id + "] found valid plugin at " + plugfile);
            if (this.state.running) {
              this.include(plugin);
            }
            this.on('running', function(include) {
              _this.include = include;
              _this.log("loading storm-compatible plugin for: " + id + "/" + plugfile);
              return _this.include(plugin);
            });
          }
        }
      } catch (err) {
        this.log(("import - [" + id + "] is not a storm compatible module: ") + err);
      }
      try {
        if (!((self != null) && self)) {
          return require("" + id);
        }
      } catch (err) {
        return this.log(("import - [" + id + "] failed with: ") + err);
      }
    };

    StormAgent.prototype.execute = function(command, callback) {
      var exec,
        _this = this;
      if (!command) {
        return callback(new Error("no valid command for execution!"));
      }
      console.log("executing " + command + "...");
      exec = require('child_process').exec;
      return exec(command, function(error, stdout, stderr) {
        if (error) {
          return callback(error);
        } else {
          return callback();
        }
      });
    };

    StormAgent.prototype.activate = function(storm, callback) {
      var count, request, srequest,
        _this = this;
      request = require('request');
      count = 0;
      srequest = function(method, url, storm, callback) {
        if ((method != null) && method instanceof Function && (url != null) && (storm != null)) {
          return method(url, function(err, res, body) {
            if (callback != null) {
              return callback(err, res, body);
            }
          }).auth(storm.skey, storm.token);
        }
      };
      return async.until(function() {
        return (_this.state.activated != null) && _this.state.activated;
      }, function(repeat) {
        count++;
        _this.log("attempting activation (try " + count + ")...");
        return async.waterfall([
          function(next) {
            if ((storm != null) && (storm.tracker != null) && (storm.skey != null) && (storm.token != null)) {
              return next(null, storm);
            }
            _this.log("discovering environment...");
            return _this.env.discover(function(storm) {
              if ((storm != null) && (storm.provider != null) && (storm.skey != null)) {
                _this.log("detected provider as: " + storm.provider + " with skey: " + storm.skey);
                if ((storm.tracker != null) && (storm.token != null)) {
                  _this.state.env = storm;
                  return next(null, storm);
                } else {
                  return next(new Error("unable to retrieve storm tracker and token data!"));
                }
              } else {
                return next(new Error("unable to discover environment!"));
              }
            });
          }, function(storm, next) {
            if (storm.id != null) {
              _this.state.id = storm.id;
              return next(null, storm);
            }
            _this.log("looking up agent ID from stormtracker... " + storm.tracker);
            return srequest(request, "" + storm.tracker + "/skey/" + storm.skey, storm, function(err, res, body) {
              var agent;
              try {
                if (err) {
                  next(err);
                }
                switch (res.statusCode) {
                  case 200:
                    agent = JSON.parse(body);
                    _this.state.id = storm.id = agent.id;
                    return next(null, storm);
                  default:
                    return next(err);
                }
              } catch (error) {
                _this.log("unable to lookup agent ID: " + error);
                return next(error);
              }
            });
          }, function(storm, next) {
            var pem, _ref;
            if ((_ref = storm.bolt) == null) {
              storm.bolt = {};
            }
            if ((storm.bolt.cert != null) || ((storm.csr != null) && (storm.bolt.key != null))) {
              return next(null, storm);
            }
            _this.log("generating CSR...");
            try {
              pem = require('pem');
              return pem.createCSR({
                country: "US",
                state: "CA",
                locality: "El Segundo",
                organization: "ClearPath Networks",
                organizationUnit: "CPN",
                commonName: storm.id,
                emailAddress: "" + storm.id + "@intercloud.net"
              }, function(err, res) {
                if ((res != null) && (res.csr != null)) {
                  _this.log("CSR generation completed:", res.csr);
                  storm.csr = res.csr;
                  storm.bolt.key = res.clientKey;
                  return next(null, storm);
                } else {
                  return new Error("CSR generation failure");
                }
              });
            } catch (error) {
              _this.log("unable to generate CSR request");
              return next(error);
            }
          }, function(storm, next) {
            var form, r;
            if ((storm.bolt.cert != null) && (storm.bolt.key != null)) {
              return next(null, storm);
            }
            _this.log("requesting CSR signing from " + storm.tracker + "...");
            r = srequest(request.post, "" + storm.tracker + "/" + storm.id + "/csr", storm, function(err, res, body) {
              try {
                switch (res.statusCode) {
                  case 200:
                    storm.bolt.cert = body;
                    return next(null, storm);
                  default:
                    return next(err);
                }
              } catch (error) {
                _this.log("unable to post CSR to get signed by stormtracker");
                return next(error);
              }
            });
            form = r.form();
            return form.append('file', storm.csr);
          }, function(storm, next) {
            if (storm.bolt.ca != null) {
              return next(null, storm);
            }
            _this.log("retrieving stormbolt configs from stormtracker...");
            return srequest(request, "" + storm.tracker + "/" + storm.id + "/bolt", storm, function(err, res, body) {
              var bolt;
              try {
                switch (res.statusCode) {
                  case 200:
                    bolt = JSON.parse(body);
                    storm.bolt = extend(storm.bolt, bolt);
                    return next(null, storm);
                  default:
                    return next(err);
                }
              } catch (error) {
                _this.log("unable to retrieve stormbolt configs");
                return next(error);
              }
            });
          }
        ], function(err, storm) {
          if (storm != null) {
            _this.log("activation completed successfully");
            _this.state.activated = true;
            _this.emit("activated", storm);
            return repeat(null, storm);
          } else {
            _this.log("error during activation: " + err);
            return setTimeout(repeat, _this.config.repeatdelay);
          }
        });
      }, function(err, storm) {
        _this.log("final call on until...");
        if (callback != null) {
          return callback(err, storm);
        }
      });
    };

    return StormAgent;

  })(EventEmitter);

  module.exports = StormAgent;

  module.exports.StormData = StormData;

  module.exports.StormRegistry = StormRegistry;

  if (typeof gc !== "undefined" && gc !== null) {
    setInterval((function() {
      return gc();
    }), 2000);
  }

}).call(this);
